### PR TITLE
migrate to pydantic v2.0

### PR DESCRIPTION
**Pull request by kizill**
My home project (Telegram-bot + python backend for serving as our village metostation and infoservice) is written on FastAPI, which recently migrated to Pydantic 2.0. I'd like to see this project also updated to Pydantic 2.0.

### CODE REVIEW

**Comment by GrandMoff100** [comment]
Oh hey. Sorry about the tests. It looks like the test environment isn't playing nice with external contributors. I'll work on fixing it

**Comment by kizill** [comment]
Hi @GrandMoff100 ! I'd guessed that, but now i'm trying to fix sphinx documentation generation errors, do you have some clues on how to fix that error? I've never worked with sphinx docs :)

**Comment by GrandMoff100** [comment]
I wonder if the autodoc for the pydantic models  isn't working with v2.

**Comment by GrandMoff100** [comment]
I think i fixed the `Unauthorized` errors by hardcoding the token (its non-sensitive anyway) so now it should be able to be used by forks. We'll just need to pull the base branch back into this branch, so the changes to the workflow file can take effect for this pr.

As for the docs, i think we didn't properly migrate to `autodoc_pydantic` 2.x.x  

For starters there's some method exclusions that should probably be changed to account for pydantic v2 methods now. 

image

I can't look into it atm, but here's the docs for autodoc pydantic if you could look into what changed with autodoc pydantic in response to pydantic v2. https://autodoc-pydantic.readthedocs.io/en/stable/users/usage.html

let me know how it goes.

**Comment by kizill** [comment]
Done with autodocs, pls review 😉

**Comment by GrandMoff100** [comment]
Yay! Reviewing now

**Review by GrandMoff100 — APPROVED** [review]

**Comment by GrandMoff100** [comment]
@kizill new release :)

https://pypi.org/project/HomeAssistant-API/4.2.1/

**Pull request merged**
