### PR TITLE
Minor fixes and removed duplicate code in asyncclient

### PR DESCRIPTION
**Pull request by FoxNerdSaysMoo**

### CODE REVIEW

**Review by GrandMoff100 — CHANGES_REQUESTED** [review]
AsyncClient super methods are not await-able.

**Comment by FoxNerdSaysMoo** [comment]
Yes they are, `Client` will use `AsyncClient`'s `request` method which is await-able. 
image
As you can see, the parent class uses the child class's methods, which in this case is the `async request()` function.

**Comment by GrandMoff100** [comment]
Ah I see. You've only changed the ones that explicitly return the request coroutine. Sounds good.

**Review by GrandMoff100 — APPROVED** [review]
Looks good but what is construct_params not a static method anymore?

**Comment by FoxNerdSaysMoo** [comment]
It's been switched to a staticmethod because it didn't use the `self` param, and was more of a utility method than an actual method for the class.

**Comment by GrandMoff100** [comment]
Epic. The Merge spaceship takes off in...

3
2
1
and merging!

**Pull request merged**
