### PR TITLE
Fix: HTTP errors not being caught correctly

### PR DESCRIPTION
**Pull request by JayDwee**
image

Errors were not being caught due to being `simplejson` instead of `json`. This should catch both

### CODE REVIEW

**Comment by GrandMoff100** [comment]
I agree. Great catch. I'm looking through your changes as we speak.

**Review by GrandMoff100 — APPROVED** [review]
Looks great!

**Review by GrandMoff100 — APPROVED** [review]
I like it.

**Comment by GrandMoff100** [comment]
Let me know when you want to merge

**Comment by JayDwee** [comment]
yep can merge now (sorry those changes i reverted were unrelated, I'm currently having issues with SSL stuff but I _think_ it's my end, not related to this repo)

**Comment by GrandMoff100** [comment]
Sounds good!

**Comment by GrandMoff100** [comment]
Friendly reminder to pull from `master` if you haven't already. I changed some things so checks run correctly on public fork pull requests. Thanks.

**Pull request merged**
