### PR TITLE
Easier way to omit ssl verification

### LINKED ISSUE #148: [Feature] Add possibility to bypass certificate verify
Good day,

what I am trying to do:
I am building an app which is in the same network of the Hass instance.
Home assistant is exposed to the web so it has an ssl certificate, 
when i make local requests I get an error :

`requests.exceptions.SSLError: HTTPSConnectionPool((Caused by SSLError(CertificateError("hostname not matching bla bla bla)))
`

I manually added to [rawclient.py on line 81](https://github.com/GrandMoff100/HomeAssistantAPI/blob/b8042bfbac9e9f0572dea68e119cd0453285442a/homeassistant_api/rawclient.py#L81)  to avoid the problem

```python
def request(
        self,
        path,
        method="GET",
        headers: Dict[str, str] = None,
        decode_bytes: bool = True,
        **kwargs,
    ) -> Any:
        """Base method for making requests to the api"""
        try:
            if self.global_request_kwargs is not None:
                kwargs.update(self.global_request_kwargs)
            logger.debug("%s request to %s", method, self.endpoint(path))
            if self.cache_session:
                resp = self.cache_session.request(
                    method,
                    self.endpoint(path),
                    headers=self.prepare_headers(headers),
                    verify=False   # -----------------------------------> verify False
                    **kwargs,
                )
        except requests.exceptions.Timeout as err:
            raise RequestTimeoutError(
                f'Home Assistant did not respond in time (timeout: {kwargs.get("timeout", 300)} sec)'
            ) from err
        return self.response_logic(response=resp, decode_bytes=decode_bytes)
```

is there any possibility to integrate the ability to set `verify=False`  in the Client class initialization?

and thank you for the api

### PR DESCRIPTION
**Pull request by mietzen**
You can now use: 
```
with Client(hass_url, hass_token, verify_ssl=False) as client:
```

instead of:

```
with Client(hass_url, hass_token, global_request_kwargs={'verify': False}) as client:
```

### CODE REVIEW

**Comment by GrandMoff100** [comment]
This is a cool idea! I'm interested in hearing more about the motivation for your idea and what your use case is like. Could you tell us more about that?

**Comment by mietzen** [comment]
> This is a cool idea! I'm interested in hearing more about the motivation for your idea and what your use case is like. Could you tell us more about that?

I wrote a Python module [(fritz-advanced-thermostat)](https://github.com/mietzen/python-fritz-advanced-thermostat) to control the offset of FRITZ!DECT30X Thermostats. The manufacture AVM is unfortunately unwilling to let us control the offset via the official API, so I'm using selenium + chromium to do so.
First I wanted to write a AppDeamon App, but spinning up a chromium instances is too much for my raspberry pi. 

So now I'm using [HomeAssistantAPI](https://github.com/GrandMoff100/HomeAssistantAPI) in combination with [fritz-advanced-thermostat](https://github.com/mietzen/python-fritz-advanced-thermostat) in a docker container on my NAS and since I'm running all my internal services on https I needed a way to disable ssl verification.

I thought adding the option in general would spare some one with a similar use case the hassle of digging through the source code.

**Comment by GrandMoff100** [comment]
Sounds awesome.

**Review by GrandMoff100 — DISMISSED** [review]
# Testing Fixes
The `verify` parameter isn't accepted by the `aiohttp.request` method, which is why some of the tests are failing, as this default parameter value is being added to all async test requests. I'd propose we move the parameter to `RawClient`, the synchronous client that uses `requests`.

# Styling Fixes
This part definitely isn't your fault but we just need to fix the type annotation for `global_request_kwargs` to `dict[str, Any] | None` in a few spots.

**Review by GrandMoff100 — DISMISSED** [review]

**Comment by GrandMoff100** [comment]
@mietzen could you add me as a collaborator with push permissions on your form so I may polish this PR to pass quality checks?

**Comment by mietzen** [comment]
Easier way to omit ssl verification by mietzen · Pull Request #145 · GrandMoff100HomeAssistantAPI

You should be good to go 👍
Sorry my time is quite limited lately, this PR went by the board.

**Comment by GrandMoff100** [comment]
No worries :+1: I got you.

**Comment by GrandMoff100** [comment]
Manually merging this because the tests pass on my machine. GitHub isn't passing the `HOMEASSISTANTAPI_TOKEN` secret from the environment to the workflow causing all of them to fail with an authentication error.

**Pull request merged**
